* TRDB -- C Model and decompression tools
  The C model accepts a stimuli file and produces the sequence of packages that
  the RTL model would do too. The C model itself is used by the testbench in
  =tb/= by employing the DPI (Direct Programming Interface) of SystemVerilog.

  The =trdb= binary provides functionality to decompress recorded packages.

** Dependencies
   Requires =libbfd.a=, =libopcodes.a=, =libiberty.a= and =libzlib.a= from
   [[https://github.com/pulp-platform/pulp-riscv-binutils-gdb][binutils]] built using the =trace_dbg_dev= branch. Build it by calling

   #+BEGIN_SRC bash
     export CFLAGS="-g -O2 -fPIC"
   ./configure --enable-targets=riscv32, x86_64-pc-linux-gnu --disable-gdb \
   --disable-ld --disable-gas --disable-gold --disable-intl --disable-gprof \
   --disable-readline --disable-sim --disable-libdecnumber
   make clean all
   #+END_SRC

** Build
   Run =make all= for a release build or =make debug= for debug symbols and more
   runtime information printed to stdout. Run =make docs= to build the
   documentation with doxygen. It will be put under =doc/=.

** Tests
   There are a few tests which can be run through =make test=.

** parse-opcodes
   The code in riscv_encoding.h was generated with [[https://github.com/pulp-platform/riscv-opcodes][riscv-opcodes]], a forked
   version which also incorporates PULP specific instructions.

** Usage
   Run =trdb --help=.
