* TRDB -- C Model and decompression tools
  The C model accepts a stimuli file and produces the sequence of packages that
  the RTL model would do too. The C model itself is used by the testbench in
  =tb/= by employing the DPI (Direct Programming Interface) of SystemVerilog.

  The =trdb= binary provides functionality to decompress recorded packages.

** Dependencies
   Requires =libbfd.a=, =libopcodes.a=, =libiberty.a= and =libzlib.a= from
   binutils built using [[https://github.com/pulp-platform/pulp-riscv-gnu-toolchain][this]] with the =trace_dbg_dev= branch. Build it by
   calling =./configure --enable-targets=riscv32, x86_64-pc-linux-gnu= and then
   =make all=.

** Build
   Run =make all= for a release build or =make debug= for debug symbols and more
   runtime information printed to stdout. Run =make docs= to build the
   documentation with doxygen. It will be put under =doc/=.

** Tests
   There are a few tests which can be run through =make test=.

** parse-opcodes
   The code in riscv_encoding.h was generated with [[https://github.com/pulp-platform/riscv-opcodes][riscv-opcodes]], a forked
   version which also incorporates PULP specific instructions.

** Usage
   Run =trdb --help=.
